name: gmcnn
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=23.3.1
  - python=3.8.15
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - cachetools==5.3.3
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cmake==3.28.3
    - contourpy==1.1.1
    - cycler==0.12.1
    - docker-pycreds==0.4.0
    - e2cnn==0.2.3
    - filelock==3.13.1
    - fonttools==4.53.1
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gitdb==4.0.11
    - gitpython==3.1.42
    - google-auth==2.28.2
    - google-auth-oauthlib==1.0.0
    - grpcio==1.62.1
    - hydra-core==1.3.2
    - idna==3.6
    - importlib-metadata==7.0.2
    - importlib-resources==6.4.0
    - iopath==0.1.10
    - jinja2==3.1.3
    - kiwisolver==1.4.5
    - lightning==2.2.1
    - lightning-bolts==0.7.0
    - lightning-utilities==0.10.1
    - lit==18.1.1
    - markdown==3.5.2
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - mpmath==1.3.0
    - multidict==6.0.5
    - networkx==3.1
    - numpy==1.24.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.4.99
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - packaging==23.2
    - pillow==10.2.0
    - portalocker==2.10.1
    - protobuf==4.25.3
    - psutil==5.9.8
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==1.9.5
    - pyyaml==6.0.1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.10.1
    - sentry-sdk==1.41.0
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - sympy==1.12
    - tabulate==0.9.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - termcolor==2.4.0
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchinfo==1.8.0
    - torchmetrics==1.3.1
    - torchvision==0.15.2
    - tqdm==4.66.2
    - triton==2.0.0
    - typing-extensions==4.10.0
    - urllib3==2.2.1
    - wandb==0.16.4
    - werkzeug==3.0.1
    - yacs==0.1.8
    - yarl==1.9.4
    - zipp==3.17.0
