# dataset: cifar10

# Model
model:
  group: cyclic
  order: 32
  nbr: 3
  lr: 0.003
  dataset: cifar10
  num_classes: 10
  dropout: 0.2
  blocks:
    - num_layers: 1
      out_channels: [120]
    - num_layers: 1
      out_channels: [120]

# Data
data:
  path: /path/to/data/cifar10/
  batch_size: 256
  num_workers: 8

# Training
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 100
  log_every_n_steps: 10

overfit:
  bs: 1
