# dataset: mnist_bg_rot

# Model
model:
  group: dihedral
  order: 14
  nbr: 2
  lr: 0.003
  dataset: mnist-bg-rot
  num_classes: 10
  dropout: 0.3
  blocks:
    - num_layers: 1
      out_channels: [120]
    - num_layers: 1
      out_channels: [120]

# Data
data:
  path: /path/to/data/mnist_bg_rot/
  batch_size: 256
  num_workers: 8

# Training
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 100
  log_every_n_steps: 10

overfit:
  bs: 1
