# dataset: "PhiFlow"

# Model
model:
  group: cyclic
  order: 64
  nbr: 1
  lr: 0.003
  dataset: PhiFlow
  out_channels: 2
  dropout: 0.2
  blocks:
    - num_layers: 1
      out_channels: [120]
    - num_layers: 1
      out_channels: [120]

data:
  batch_size: 32
  num_workers: 4
  input_length: 10
  mid: 22
  output_length: 6
  direc: "/path/to/data"
  train_task: [(48, 10), (56, 10), (8, 20),  (40, 5),  (56, 25), 
                      (48, 20), (48, 5),  (16, 20), (56, 5),  (32, 10), 
                      (56, 15), (16, 5),  (40, 15), (40, 25), (48, 25), 
                      (48, 15), (24, 10), (56, 20), (32, 15), (16, 15),
                      (8, 10),  (24, 15), (8, 15),  (32, 25), (8, 5)]
  test_domain_task: [(32, 20), (32, 5), (24, 20), (16, 25), (24, 5), 
                            (16, 10), (40, 20), (8, 25), (24, 25), (40, 10)]
  valid_task: [(48, 10), (56, 10), (8, 20),  (40, 5),  (56, 25), 
                      (48, 20), (48, 5),  (16, 20), (56, 5),  (32, 10), 
                      (56, 15), (16, 5),  (40, 15), (40, 25), (48, 25), 
                      (48, 15), (24, 10), (56, 20), (32, 15), (16, 15),
                      (8, 10),  (24, 15), (8, 15),  (32, 25), (8, 5)]
  test_future_task: [(48, 10), (56, 10), (8, 20),  (40, 5),  (56, 25), 
                            (48, 20), (48, 5),  (16, 20), (56, 5),  (32, 10), 
                            (56, 15), (16, 5),  (40, 15), (40, 25), (48, 25), 
                            (48, 15), (24, 10), (56, 20), (32, 15), (16, 15),
                            (8, 10),  (24, 15), (8, 15),  (32, 25), (8, 5)]
  train_time: [0, 160]
  valid_time: [160, 200]
  test_future_time: [200, 250]
  test_domain_time: [0, 100]
  stack: true

trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 100
  log_every_n_steps: 10

overfit:
  bs: 1