# dataset: rectangles

# Model
model:
  group: cyclic
  order: 28
  nbr: 3
  lr: 0.003
  dataset: rect
  num_classes: 2
  dropout: 0.3
  blocks:
    - num_layers: 1
      out_channels: [120]
    - num_layers: 1
      out_channels: [120]

# Data
data:
  path: /path/to/data/rectangles/
  batch_size: 512
  num_workers: 4

# Training
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 100
  log_every_n_steps: 10

overfit:
  bs: 1
