# Config for ImplicitCNN

# Model
model:
  group: cyclic
  order: 28
  nbr: 3
  lr: 0.003
  dataset: rect
  num_classes: 2
  dropout: 0.3
  num_layers: 3
  out_channels: [120, 120]

# Data
data:
  batch_size: 512
  num_workers: 4

# Training
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 100
  log_every_n_steps: 10

tester:
  accelerator: gpu
  devices: 1
  num_nodes: 1

overfit:
  bs: 1
